version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: job_postings
      POSTGRES_USER: data_analyst
      POSTGRES_PASSWORD: top_secret
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
      - ./sql/0_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
